deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -41,6 +41,13 @@ jobs:
             | jq -r '.artifacts | map(select(.name == "core_sha")) | .[0].archive_download_url')
           curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o core_sha.zip $core_sha_url
           unzip core_sha.zip
+          echo "Current directory: $(pwd)"  # 현재 디렉토리 출력
+          ls -l  # 현재 디렉토리의 파일 목록 출력
+          if [ ! -f core_sha.txt ]; then
+            echo "Error: core_sha.txt not found."
+            exit 1
+          fi
+          cat core_sha.txt
 
       - name: Download MySQL SHA artifact
         run: |
@@ -49,6 +56,13 @@ jobs:
             | jq -r '.artifacts | map(select(.name == "mysql_sha")) | .[0].archive_download_url')
           curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o mysql_sha.zip $mysql_sha_url
           unzip mysql_sha.zip
+          echo "Current directory: $(pwd)"  # 현재 디렉토리 출력
+          ls -l  # 현재 디렉토리의 파일 목록 출력
+          if [ ! -f mysql_sha.txt ]; then
+            echo "Error: mysql_sha.txt not found."
+            exit 1
+          fi
+          cat mysql_sha.txt
 
       - name: Login to Docker Hub
         uses: docker/login-action@v1
